#!/bin/bash

FILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)

URL="http://i.bo0tzz.me/$FILENAME.png"
FILENAME="/home/boet/Pictures/Screenshots/$FILENAME.png"

scrot -sm $FILENAME

scp $FILENAME unraid:/mnt/user/appdata/bo0tzz.me/web/img/

echo $URL | xclip -selection c

notify-send "URL copied to clipboard"
