#!/usr/bin/env bash

FILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)

URL="http://i.bo0tzz.me/"$FILENAME.png
FILENAME=~/Pictures/Screenshots/$FILENAME.png

maim -sm 10 $FILENAME

scp $FILENAME vps:~/docker/nginx/web/img/

echo $URL | tr -d '\n' | xclip -selection c

notify-send "URL copied to clipboard"
